domain_path: /home/wstanislaus/git/Xilinx_KR260_Projects/gpio_led/RPU/platform/export/platform/sw/freertos_psu_cortexr5_0
app_src_dir: /tools/Xilinx/2025.2/Vitis/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
lang: c
