#ifndef XMEM_CONFIG_H_
#define XMEM_CONFIG_H_

#define XPAR_PSU_DDR_0_BASEADDRESS 0x100000
#define XPAR_PSU_DDR_0_HIGHADDRESS 0x7ffffffe
#define XPAR_PSU_OCM_0_BASEADDRESS 0xfffc0000
#define XPAR_PSU_OCM_0_HIGHADDRESS 0xffffffff

#endif